apiVersion: v1
kind: Secret
metadata:
  name: sample-grafana-datasource
#  namespace: monitoring
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server:80
      basicAuth: false
      isDefault: true
      version: 1
      editable: true