apiVersion: v1
kind: Secret
metadata:
  name: event-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  helmsecretdemo: '{{ .Values.helmsecretdemo }}'