# Use config map for not-secret configuration data

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centralconfig.fullname" . }}-configmap
data:
  {{- toYaml .Values.environments | nindent 2 }}