apiVersion: v1
kind: Service
metadata:
  name: {{ include "centralconfig.fullname" . }}-clusterip
  labels:
    {{- include "centralconfig.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "centralconfig.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
#      nodePort: 31119